### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by Colin66** [eben80/ESP32-CAM-Print-Monitor#1]
Hi, the project looks really good, is the functionality already as shown in the video, i.e. it can already abort the print via the network ?
Is the usb to serial just to program the ESP32  ?
Do you have much hope of adding network write to sd card ?
Thanks and keep it up !

**Comment by eben80** [comment]
Hi Colin!
Thanks for the kind words. 
Yes it can abort the print and currently also switch off the power to the printer remotely if you have the relay in the circuit.
The USB to serial is just used for programming although OTA also works so its not required after first flash.

The SD card write over network will be the most difficult. 
Currently I'm working on the custom GCODE code, the autoscrolling and multi-line responses from the printer is giving me a headache....
